(cl:defpackage image_recognition_msgs-msg
  (:use )
  (:export
   "<ANNOTATION>"
   "ANNOTATION"
   "<CATEGORICALDISTRIBUTION>"
   "CATEGORICALDISTRIBUTION"
   "<CATEGORYPROBABILITY>"
   "CATEGORYPROBABILITY"
   "<FACEPROPERTIES>"
   "FACEPROPERTIES"
   "<RECOGNITION>"
   "RECOGNITION"
   "<RECOGNITIONS>"
   "RECOGNITIONS"
  ))

