// Generated by gencpp from file image_recognition_msgs/FaceProperties.msg
// DO NOT EDIT!


#ifndef IMAGE_RECOGNITION_MSGS_MESSAGE_FACEPROPERTIES_H
#define IMAGE_RECOGNITION_MSGS_MESSAGE_FACEPROPERTIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_recognition_msgs
{
template <class ContainerAllocator>
struct FaceProperties_
{
  typedef FaceProperties_<ContainerAllocator> Type;

  FaceProperties_()
    : gender(0)
    , age(0)  {
    }
  FaceProperties_(const ContainerAllocator& _alloc)
    : gender(0)
    , age(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gender_type;
  _gender_type gender;

   typedef uint8_t _age_type;
  _age_type age;


    enum { MALE = 0u };
     enum { FEMALE = 1u };
 

  typedef boost::shared_ptr< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> const> ConstPtr;

}; // struct FaceProperties_

typedef ::image_recognition_msgs::FaceProperties_<std::allocator<void> > FaceProperties;

typedef boost::shared_ptr< ::image_recognition_msgs::FaceProperties > FacePropertiesPtr;
typedef boost::shared_ptr< ::image_recognition_msgs::FaceProperties const> FacePropertiesConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_recognition_msgs::FaceProperties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_recognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'image_recognition_msgs': ['/home/nvidia/zuckbot_ws/src/image_recognition/image_recognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0509e719654f194b1f2f178434bcb902";
  }

  static const char* value(const ::image_recognition_msgs::FaceProperties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0509e719654f194bULL;
  static const uint64_t static_value2 = 0x1f2f178434bcb902ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_recognition_msgs/FaceProperties";
  }

  static const char* value(const ::image_recognition_msgs::FaceProperties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Face properties\n\
\n\
# Gender definitions\n\
uint8 MALE=0\n\
uint8 FEMALE=1\n\
\n\
# Gender, either MALE of FEMALE\n\
uint8 gender\n\
\n\
# The age of the face\n\
uint8 age\n\
";
  }

  static const char* value(const ::image_recognition_msgs::FaceProperties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gender);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceProperties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_recognition_msgs::FaceProperties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_recognition_msgs::FaceProperties_<ContainerAllocator>& v)
  {
    s << indent << "gender: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gender);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_RECOGNITION_MSGS_MESSAGE_FACEPROPERTIES_H
