// Generated by gencpp from file image_recognition_msgs/GetFacePropertiesRequest.msg
// DO NOT EDIT!


#ifndef IMAGE_RECOGNITION_MSGS_MESSAGE_GETFACEPROPERTIESREQUEST_H
#define IMAGE_RECOGNITION_MSGS_MESSAGE_GETFACEPROPERTIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace image_recognition_msgs
{
template <class ContainerAllocator>
struct GetFacePropertiesRequest_
{
  typedef GetFacePropertiesRequest_<ContainerAllocator> Type;

  GetFacePropertiesRequest_()
    : face_image_array()  {
    }
  GetFacePropertiesRequest_(const ContainerAllocator& _alloc)
    : face_image_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _face_image_array_type;
  _face_image_array_type face_image_array;




  typedef boost::shared_ptr< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFacePropertiesRequest_

typedef ::image_recognition_msgs::GetFacePropertiesRequest_<std::allocator<void> > GetFacePropertiesRequest;

typedef boost::shared_ptr< ::image_recognition_msgs::GetFacePropertiesRequest > GetFacePropertiesRequestPtr;
typedef boost::shared_ptr< ::image_recognition_msgs::GetFacePropertiesRequest const> GetFacePropertiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_recognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'image_recognition_msgs': ['/home/nvidia/zuckbot_ws/src/image_recognition/image_recognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3bad4931a01d73662add4a92636467c";
  }

  static const char* value(const ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3bad4931a01d736ULL;
  static const uint64_t static_value2 = 0x62add4a92636467cULL;
};

template<class ContainerAllocator>
struct DataType< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_recognition_msgs/GetFacePropertiesRequest";
  }

  static const char* value(const ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
sensor_msgs/Image[] face_image_array\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.face_image_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFacePropertiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_recognition_msgs::GetFacePropertiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "face_image_array[]" << std::endl;
    for (size_t i = 0; i < v.face_image_array.size(); ++i)
    {
      s << indent << "  face_image_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.face_image_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_RECOGNITION_MSGS_MESSAGE_GETFACEPROPERTIESREQUEST_H
