teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.2
  scale_linear_turbo: 1
  axis_angular: 0
  scale_angular: 0.5
  scale_angular_turbo: 1
  enable_button: 1 #L2 trigger
  enable_turbo_button: 4 #L1 trigger
  

