(cl:defpackage image_recognition_msgs-srv
  (:use )
  (:export
   "ANNOTATE"
   "<ANNOTATE-REQUEST>"
   "ANNOTATE-REQUEST"
   "<ANNOTATE-RESPONSE>"
   "ANNOTATE-RESPONSE"
   "GETFACEPROPERTIES"
   "<GETFACEPROPERTIES-REQUEST>"
   "GETFACEPROPERTIES-REQUEST"
   "<GETFACEPROPERTIES-RESPONSE>"
   "GETFACEPROPERTIES-RESPONSE"
   "RECOGNIZE"
   "<RECOGNIZE-REQUEST>"
   "RECOGNIZE-REQUEST"
   "<RECOGNIZE-RESPONSE>"
   "RECOGNIZE-RESPONSE"
  ))

