// Generated by gencpp from file roboteq_control/ControlStatus.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_CONTROL_MESSAGE_CONTROLSTATUS_H
#define ROBOTEQ_CONTROL_MESSAGE_CONTROLSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboteq_control
{
template <class ContainerAllocator>
struct ControlStatus_
{
  typedef ControlStatus_<ContainerAllocator> Type;

  ControlStatus_()
    : header()
    , pwm(0.0)
    , reference(0.0)
    , feedback(0.0)
    , loop_error(0.0)  {
    }
  ControlStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pwm(0.0)
    , reference(0.0)
    , feedback(0.0)
    , loop_error(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pwm_type;
  _pwm_type pwm;

   typedef double _reference_type;
  _reference_type reference;

   typedef double _feedback_type;
  _feedback_type feedback;

   typedef double _loop_error_type;
  _loop_error_type loop_error;




  typedef boost::shared_ptr< ::roboteq_control::ControlStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_control::ControlStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ControlStatus_

typedef ::roboteq_control::ControlStatus_<std::allocator<void> > ControlStatus;

typedef boost::shared_ptr< ::roboteq_control::ControlStatus > ControlStatusPtr;
typedef boost::shared_ptr< ::roboteq_control::ControlStatus const> ControlStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_control::ControlStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_control::ControlStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboteq_control': ['/home/nvidia/zuckbot_ws/src/roboteq_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::ControlStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::ControlStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::ControlStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::ControlStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::ControlStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::ControlStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_control::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67f973d0cebdda296868bd3530b250ad";
  }

  static const char* value(const ::roboteq_control::ControlStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67f973d0cebdda29ULL;
  static const uint64_t static_value2 = 0x6868bd3530b250adULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_control::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_control/ControlStatus";
  }

  static const char* value(const ::roboteq_control::ControlStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_control::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 50Hz feedback message for controls purposes\n\
Header header\n\
\n\
# PWM\n\
float64 pwm\n\
\n\
# reference\n\
float64 reference\n\
\n\
# feedback\n\
float64 feedback\n\
\n\
# Loop error\n\
float64 loop_error\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboteq_control::ControlStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_control::ControlStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pwm);
      stream.next(m.reference);
      stream.next(m.feedback);
      stream.next(m.loop_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_control::ControlStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_control::ControlStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pwm: ";
    Printer<double>::stream(s, indent + "  ", v.pwm);
    s << indent << "reference: ";
    Printer<double>::stream(s, indent + "  ", v.reference);
    s << indent << "feedback: ";
    Printer<double>::stream(s, indent + "  ", v.feedback);
    s << indent << "loop_error: ";
    Printer<double>::stream(s, indent + "  ", v.loop_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_CONTROL_MESSAGE_CONTROLSTATUS_H
