// Generated by gencpp from file roboteq_control/MotorStatus.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_CONTROL_MESSAGE_MOTORSTATUS_H
#define ROBOTEQ_CONTROL_MESSAGE_MOTORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboteq_control
{
template <class ContainerAllocator>
struct MotorStatus_
{
  typedef MotorStatus_<ContainerAllocator> Type;

  MotorStatus_()
    : header()
    , volts(0.0)
    , amps_motor(0.0)
    , amps_batt(0.0)
    , track(0.0)  {
    }
  MotorStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , volts(0.0)
    , amps_motor(0.0)
    , amps_batt(0.0)
    , track(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _volts_type;
  _volts_type volts;

   typedef double _amps_motor_type;
  _amps_motor_type amps_motor;

   typedef double _amps_batt_type;
  _amps_batt_type amps_batt;

   typedef double _track_type;
  _track_type track;




  typedef boost::shared_ptr< ::roboteq_control::MotorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_control::MotorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatus_

typedef ::roboteq_control::MotorStatus_<std::allocator<void> > MotorStatus;

typedef boost::shared_ptr< ::roboteq_control::MotorStatus > MotorStatusPtr;
typedef boost::shared_ptr< ::roboteq_control::MotorStatus const> MotorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_control::MotorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_control::MotorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboteq_control': ['/home/nvidia/zuckbot_ws/src/roboteq_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_control::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f79b5306cd75663999e1a992e3b8a85e";
  }

  static const char* value(const ::roboteq_control::MotorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf79b5306cd756639ULL;
  static const uint64_t static_value2 = 0x99e1a992e3b8a85eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_control::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_control/MotorStatus";
  }

  static const char* value(const ::roboteq_control::MotorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_control::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 50Hz feedback message for controls purposes\n\
Header header\n\
\n\
# Electrical power supply to the driver (V)\n\
float64 volts\n\
\n\
# Current flowing in the motors (A)\n\
float64 amps_motor\n\
float64 amps_batt\n\
\n\
# Tracks\n\
float64 track\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboteq_control::MotorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_control::MotorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.volts);
      stream.next(m.amps_motor);
      stream.next(m.amps_batt);
      stream.next(m.track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_control::MotorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_control::MotorStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "volts: ";
    Printer<double>::stream(s, indent + "  ", v.volts);
    s << indent << "amps_motor: ";
    Printer<double>::stream(s, indent + "  ", v.amps_motor);
    s << indent << "amps_batt: ";
    Printer<double>::stream(s, indent + "  ", v.amps_batt);
    s << indent << "track: ";
    Printer<double>::stream(s, indent + "  ", v.track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_CONTROL_MESSAGE_MOTORSTATUS_H
