// Generated by gencpp from file roboteq_control/Peripheral.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_CONTROL_MESSAGE_PERIPHERAL_H
#define ROBOTEQ_CONTROL_MESSAGE_PERIPHERAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboteq_control
{
template <class ContainerAllocator>
struct Peripheral_
{
  typedef Peripheral_<ContainerAllocator> Type;

  Peripheral_()
    : header()
    , pulse_in()
    , analog()
    , digital_in()
    , digital_out()  {
    }
  Peripheral_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pulse_in(_alloc)
    , analog(_alloc)
    , digital_in(_alloc)
    , digital_out(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _pulse_in_type;
  _pulse_in_type pulse_in;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _analog_type;
  _analog_type analog;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _digital_in_type;
  _digital_in_type digital_in;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _digital_out_type;
  _digital_out_type digital_out;




  typedef boost::shared_ptr< ::roboteq_control::Peripheral_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_control::Peripheral_<ContainerAllocator> const> ConstPtr;

}; // struct Peripheral_

typedef ::roboteq_control::Peripheral_<std::allocator<void> > Peripheral;

typedef boost::shared_ptr< ::roboteq_control::Peripheral > PeripheralPtr;
typedef boost::shared_ptr< ::roboteq_control::Peripheral const> PeripheralConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_control::Peripheral_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_control::Peripheral_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboteq_control': ['/home/nvidia/zuckbot_ws/src/roboteq_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::Peripheral_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::Peripheral_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::Peripheral_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::Peripheral_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::Peripheral_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::Peripheral_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_control::Peripheral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c04fdd000fd83fd2a224fbc2a13fdda";
  }

  static const char* value(const ::roboteq_control::Peripheral_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c04fdd000fd83fdULL;
  static const uint64_t static_value2 = 0x2a224fbc2a13fddaULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_control::Peripheral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_control/Peripheral";
  }

  static const char* value(const ::roboteq_control::Peripheral_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_control::Peripheral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
#GPIO\n\
\n\
#Pulse in [pag. 256]\n\
uint16[] pulse_in\n\
\n\
#Analog in [pag. 231]\n\
float64[] analog\n\
\n\
#Digital input [pag. 242]\n\
uint8[] digital_in\n\
\n\
#Digital outut [pag. 242]\n\
uint8[] digital_out\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboteq_control::Peripheral_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_control::Peripheral_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pulse_in);
      stream.next(m.analog);
      stream.next(m.digital_in);
      stream.next(m.digital_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Peripheral_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_control::Peripheral_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_control::Peripheral_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pulse_in[]" << std::endl;
    for (size_t i = 0; i < v.pulse_in.size(); ++i)
    {
      s << indent << "  pulse_in[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.pulse_in[i]);
    }
    s << indent << "analog[]" << std::endl;
    for (size_t i = 0; i < v.analog.size(); ++i)
    {
      s << indent << "  analog[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.analog[i]);
    }
    s << indent << "digital_in[]" << std::endl;
    for (size_t i = 0; i < v.digital_in.size(); ++i)
    {
      s << indent << "  digital_in[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.digital_in[i]);
    }
    s << indent << "digital_out[]" << std::endl;
    for (size_t i = 0; i < v.digital_out.size(); ++i)
    {
      s << indent << "  digital_out[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.digital_out[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_CONTROL_MESSAGE_PERIPHERAL_H
