//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the roboteq_control package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __roboteq_control__ROBOTEQPARAMETERCONFIG_H__
#define __roboteq_control__ROBOTEQPARAMETERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace roboteq_control
{
  class RoboteqParameterConfigStatics;
  
  class RoboteqParameterConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(RoboteqParameterConfig &config, const RoboteqParameterConfig &max, const RoboteqParameterConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RoboteqParameterConfig &config1, const RoboteqParameterConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RoboteqParameterConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RoboteqParameterConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RoboteqParameterConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RoboteqParameterConfig &config) const = 0;
      virtual void getValue(const RoboteqParameterConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T RoboteqParameterConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (RoboteqParameterConfig::* field);

      virtual void clamp(RoboteqParameterConfig &config, const RoboteqParameterConfig &max, const RoboteqParameterConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RoboteqParameterConfig &config1, const RoboteqParameterConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RoboteqParameterConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RoboteqParameterConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RoboteqParameterConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RoboteqParameterConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RoboteqParameterConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RoboteqParameterConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RoboteqParameterConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<RoboteqParameterConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RoboteqParameterConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("ratio"==(*_i)->name){ratio = boost::any_cast<double>(val);}
        if("rotation"==(*_i)->name){rotation = boost::any_cast<int>(val);}
        if("stall_detection"==(*_i)->name){stall_detection = boost::any_cast<int>(val);}
        if("amper_limit"==(*_i)->name){amper_limit = boost::any_cast<double>(val);}
        if("max_forward"==(*_i)->name){max_forward = boost::any_cast<int>(val);}
        if("max_reverse"==(*_i)->name){max_reverse = boost::any_cast<int>(val);}
        if("max_speed"==(*_i)->name){max_speed = boost::any_cast<double>(val);}
        if("max_acceleration"==(*_i)->name){max_acceleration = boost::any_cast<double>(val);}
        if("max_deceleration"==(*_i)->name){max_deceleration = boost::any_cast<double>(val);}
        if("load_roboteq"==(*_i)->name){load_roboteq = boost::any_cast<bool>(val);}
        if("restore_defaults"==(*_i)->name){restore_defaults = boost::any_cast<bool>(val);}
      }
    }

    double ratio;
int rotation;
int stall_detection;
double amper_limit;
int max_forward;
int max_reverse;
double max_speed;
double max_acceleration;
double max_deceleration;
bool load_roboteq;
bool restore_defaults;

    bool state;
    std::string name;

    
}groups;



//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ratio;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int rotation;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int stall_detection;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double amper_limit;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_forward;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_reverse;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_speed;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_acceleration;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_deceleration;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool load_roboteq;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool restore_defaults;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RoboteqParameterConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RoboteqParameterConfig &__max__ = __getMax__();
      const RoboteqParameterConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RoboteqParameterConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RoboteqParameterConfig &__getDefault__();
    static const RoboteqParameterConfig &__getMax__();
    static const RoboteqParameterConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const RoboteqParameterConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void RoboteqParameterConfig::ParamDescription<std::string>::clamp(RoboteqParameterConfig &config, const RoboteqParameterConfig &max, const RoboteqParameterConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class RoboteqParameterConfigStatics
  {
    friend class RoboteqParameterConfig;
    
    RoboteqParameterConfigStatics()
    {
RoboteqParameterConfig::GroupDescription<RoboteqParameterConfig::DEFAULT, RoboteqParameterConfig> Default("Default", "", 0, 0, true, &RoboteqParameterConfig::groups);
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ratio = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ratio = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ratio = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("ratio", "double", 0, "[#] Gear ratio", "", &RoboteqParameterConfig::ratio)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("ratio", "double", 0, "[#] Gear ratio", "", &RoboteqParameterConfig::ratio)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rotation = -1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rotation = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rotation = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("rotation", "int", 0, "Versus of the rotation of the motor", "{'enum_description': 'Rotation versus wheel', 'enum': [{'srcline': 10, 'description': 'Clockwise rotation', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': -1, 'ctype': 'int', 'type': 'int', 'name': 'Clockwise'}, {'srcline': 11, 'description': 'Counterclockwise rotation', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Counterclockwise'}]}", &RoboteqParameterConfig::rotation)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("rotation", "int", 0, "Versus of the rotation of the motor", "{'enum_description': 'Rotation versus wheel', 'enum': [{'srcline': 10, 'description': 'Clockwise rotation', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': -1, 'ctype': 'int', 'type': 'int', 'name': 'Clockwise'}, {'srcline': 11, 'description': 'Counterclockwise rotation', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Counterclockwise'}]}", &RoboteqParameterConfig::rotation)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stall_detection = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stall_detection = 3;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stall_detection = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("stall_detection", "int", 0, "Stall detection", "{'enum_description': 'Stall configuration', 'enum': [{'srcline': 15, 'description': 'Disabled', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Disabled'}, {'srcline': 16, 'description': '250ms at 10% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '250ms_at_10percent'}, {'srcline': 17, 'description': '500ms at 25% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': '500ms_at_25percent'}, {'srcline': 18, 'description': '1000ms at 50% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '1000ms_at_50percent'}]}", &RoboteqParameterConfig::stall_detection)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("stall_detection", "int", 0, "Stall detection", "{'enum_description': 'Stall configuration', 'enum': [{'srcline': 15, 'description': 'Disabled', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Disabled'}, {'srcline': 16, 'description': '250ms at 10% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '250ms_at_10percent'}, {'srcline': 17, 'description': '500ms at 25% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': '500ms_at_25percent'}, {'srcline': 18, 'description': '1000ms at 50% power', 'srcfile': '/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '1000ms_at_50percent'}]}", &RoboteqParameterConfig::stall_detection)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.amper_limit = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.amper_limit = 20.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.amper_limit = 5.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("amper_limit", "double", 0, "[A] Amper limit", "", &RoboteqParameterConfig::amper_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("amper_limit", "double", 0, "[A] Amper limit", "", &RoboteqParameterConfig::amper_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_forward = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_forward = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_forward = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("max_forward", "int", 0, "[%] IN MODULE - Maximum power forward", "", &RoboteqParameterConfig::max_forward)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("max_forward", "int", 0, "[%] IN MODULE - Maximum power forward", "", &RoboteqParameterConfig::max_forward)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_reverse = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_reverse = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_reverse = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("max_reverse", "int", 0, "[%] IN MODULE - Maximum power reverse", "", &RoboteqParameterConfig::max_reverse)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<int>("max_reverse", "int", 0, "[%] IN MODULE - Maximum power reverse", "", &RoboteqParameterConfig::max_reverse)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_speed = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_speed = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_speed = 10.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_speed", "double", 0, "[RPM] max motor speed (after gear reduction)", "", &RoboteqParameterConfig::max_speed)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_speed", "double", 0, "[RPM] max motor speed (after gear reduction)", "", &RoboteqParameterConfig::max_speed)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_acceleration = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_acceleration = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_acceleration = 1000.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_acceleration", "double", 0, "[RPM/s] max motor acceleration (after gear reduction)", "", &RoboteqParameterConfig::max_acceleration)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_acceleration", "double", 0, "[RPM/s] max motor acceleration (after gear reduction)", "", &RoboteqParameterConfig::max_acceleration)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_deceleration = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_deceleration = std::numeric_limits<double>::infinity();
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_deceleration = 1000.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_deceleration", "double", 0, "[RPM/s] max motor deceleration (after gear reduction)", "", &RoboteqParameterConfig::max_deceleration)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<double>("max_deceleration", "double", 0, "[RPM/s] max motor deceleration (after gear reduction)", "", &RoboteqParameterConfig::max_deceleration)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.load_roboteq = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.load_roboteq = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.load_roboteq = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<bool>("load_roboteq", "bool", 0, "Load all parameters from Roboteq board", "", &RoboteqParameterConfig::load_roboteq)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<bool>("load_roboteq", "bool", 0, "Load all parameters from Roboteq board", "", &RoboteqParameterConfig::load_roboteq)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.restore_defaults = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.restore_defaults = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.restore_defaults = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Restore to the original configuration", "", &RoboteqParameterConfig::restore_defaults)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboteqParameterConfig::AbstractParamDescriptionConstPtr(new RoboteqParameterConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Restore to the original configuration", "", &RoboteqParameterConfig::restore_defaults)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RoboteqParameterConfig::AbstractGroupDescriptionConstPtr(new RoboteqParameterConfig::GroupDescription<RoboteqParameterConfig::DEFAULT, RoboteqParameterConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RoboteqParameterConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<RoboteqParameterConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RoboteqParameterConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RoboteqParameterConfig __max__;
    RoboteqParameterConfig __min__;
    RoboteqParameterConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RoboteqParameterConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RoboteqParameterConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RoboteqParameterConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const RoboteqParameterConfig &RoboteqParameterConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const RoboteqParameterConfig &RoboteqParameterConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const RoboteqParameterConfig &RoboteqParameterConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<RoboteqParameterConfig::AbstractParamDescriptionConstPtr> &RoboteqParameterConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RoboteqParameterConfig::AbstractGroupDescriptionConstPtr> &RoboteqParameterConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RoboteqParameterConfigStatics *RoboteqParameterConfig::__get_statics__()
  {
    const static RoboteqParameterConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RoboteqParameterConfigStatics::get_instance();
    
    return statics;
  }

//#line 10 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_Clockwise = -1;
//#line 11 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_Counterclockwise = 1;
//#line 15 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_Disabled = 0;
//#line 16 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_250ms_at_10percent = 1;
//#line 17 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_500ms_at_25percent = 2;
//#line 18 "/home/nvidia/zuckbot_ws/src/roboteq_control/cfg/RoboteqParameter.cfg"
      const int RoboteqParameter_1000ms_at_50percent = 3;
}

#endif // __ROBOTEQPARAMETERRECONFIGURATOR_H__
