// Generated by gencpp from file roboteq_control/ServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_CONTROL_MESSAGE_SERVICEREQUEST_H
#define ROBOTEQ_CONTROL_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboteq_control
{
template <class ContainerAllocator>
struct ServiceRequest_
{
  typedef ServiceRequest_<ContainerAllocator> Type;

  ServiceRequest_()
    : service()  {
    }
  ServiceRequest_(const ContainerAllocator& _alloc)
    : service(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _service_type;
  _service_type service;




  typedef boost::shared_ptr< ::roboteq_control::ServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_control::ServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceRequest_

typedef ::roboteq_control::ServiceRequest_<std::allocator<void> > ServiceRequest;

typedef boost::shared_ptr< ::roboteq_control::ServiceRequest > ServiceRequestPtr;
typedef boost::shared_ptr< ::roboteq_control::ServiceRequest const> ServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_control::ServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_control::ServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboteq_control': ['/home/nvidia/zuckbot_ws/src/roboteq_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_control::ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_control::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_control::ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cbcfa13b08f6d36710b9af8741e6112";
  }

  static const char* value(const ::roboteq_control::ServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cbcfa13b08f6d36ULL;
  static const uint64_t static_value2 = 0x710b9af8741e6112ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_control/ServiceRequest";
  }

  static const char* value(const ::roboteq_control::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string service\n\
";
  }

  static const char* value(const ::roboteq_control::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.service);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_control::ServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_control::ServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "service: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.service);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_CONTROL_MESSAGE_SERVICEREQUEST_H
